tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "garethr/kubeval"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "int128/kubelogin"
tap "warrensbox/tap"
tap "wallix/awless"
tap "tylerbrock/saw"

brew "awless"
brew "aws-iam-authenticator"
brew "awscli"
# brew "bash"
brew "bash-completion"
brew "coreutils"
brew "curl"
brew "k9s"
brew "ddrescue"
# brew "dep" # # not found. Failure on MacBook M1
brew "diffutils"
brew "direnv"
brew "findutils"
brew "fasd"
brew "gawk"
brew "gettext"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "go"
brew "gradle"
brew "grep"
brew "gzip"
brew "helm@2"
brew "htop"
brew "jenv"
brew "jq"
brew "k9s"
brew "kind"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "nmap"
brew "openssh"
brew "openssl@1.1"
brew "p7zip"
# brew "packer" # not found. Failure on MacBook M1
brew "parallel"
brew "python"
brew "rename"
brew "rsync"
brew "saw"
brew "screen"
brew "sipcalc"
# brew "shellcheck" # not found. Failure on MacBook M1
brew "ssh-copy-id"
brew "svn" # required by font-source-code-pro
brew "telnet"
brew "tfswitch"
brew "tmux"
brew "vim"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "yq"
brew "ykman"
brew "garethr/kubeval/kubeval"

cask "adobe-acrobat-reader"
cask "docker"
cask "font-source-code-pro"
cask "gimp"
cask "firefox"
cask "iterm2"
cask "java"
cask "postman"
# cask "tunnelblick"
cask "vagrant"
cask "vagrant-manager"
cask "virtualbox"
cask "visual-studio-code"
cask "wireshark"
