#!/bin/bash

# environment
export GRADLE_OPTS=-Dhttp.nonProxyHosts=*.guidewire.com
export IDEA_HOME=/Applications/IntelliJ\ IDEA\ U-2019.1.4-jbr11.app/Contents/
export GOPATH=/Users/hgontijo/projects/go

export JAVA_VERSION=11
export GOROOT=/usr/local/opt/go/libexec

# Ensure the GNU tools are loaded first into the PATH
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
# export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH:$GOROOT/bin:$GOPATH/bin"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/gnu-which/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/gettext/bin:$PATH"
