#!/bin/bash

# environment
export GRADLE_OPTS=-Dhttp.nonProxyHosts=*.guidewire.com
export IDEA_HOME=/Applications/IntelliJ\ IDEA\ 15.app/Contents/
export GOPATH=/Users/hgontijo/projects/go
export VAGRANT_VMS=/Users/hgontijo/projects/vms

export JAVA_VERSION=1.8
export GOROOT=/usr/local/opt/go/libexec

# Ensure the GNU tools are loaded first into the PATH
export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH:$GOROOT/bin:$GOPATH/bin"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/gnu-which/libexec/gnubin:$PATH"