#!/bin/bash
# shell.d bash completion

source <(kubectl completion bash)

complete -C aws_completer aws

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi