#!/bin/bash
# shell.d environment

export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export JAVA18_AMD64_HOME=$(/usr/libexec/java_home -v 1.8)

export P4EDITOR=vim

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad