#!/bin/bash
# shell.d environment

# Configure a file "__local" and set the JAVA_VERSION
if [ $JAVA_VERSION ]; then
  export JAVA_HOME=$(/usr/libexec/java_home -v $JAVA_VERSION)
  export JAVA18_AMD64_HOME=$(/usr/libexec/java_home -v $JAVA_VERSION)
fi

export P4EDITOR=vim

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Preserve bash history in multiple terminal windows
export HISTCONTROL=ignoredups:erasedups  # no duplicate entries
export HISTSIZE=100000                   # big big history
export HISTFILESIZE=100000               # big big history
# export HISTTIMEFORMAT="%h %d %H:%M:%S> "
# Save and reload the history after each command finishes
# >>> Disabled in here since it's already being done by Guidewire's CCS dotfiles <<<
# export PROMPT_COMMAND="$PROMPT_COMMAND;history -a; history -c; history -r"

# Override set_ps1() done by Guidewire's CCS dotfiles
set_ps1() { echo -n ""; }


export SSH_INSECURE='-o StrictHostKeyChecking=no'
