#!/bin/bash
# iset -e

# base
#   Provides basic setup

function base() {
  brew update
  brew tap caskroom/cask
  brew tap caskroom/fonts
  brew install caskroom/cask/java
  brew install caskroom/cask/iterm2
  brew cask install font-source-code-pro
  brew cask install minikube
  brew install \
    arpack \
    atk \
    aws-shell \
    awscli \
    bash \
    bash-completion \
    bison \
    cairo \
    check \
    consul \
    coreutils \
    cowsay \
    cscope \
    curl \
    d-bus \
    dbus \
    ddrescue \
    diffutils \
    docker-swarm \
    ed \
    epstool \
    ffmpeg \
    fftw \
    findutils \
    fltk \
    fontconfig \
    freetype \
    gawk \
    gcc \
    gd \
    gdbm \
    gdk-pixbuf \
    gettext \
    ghostscript \
    git \
    gl2ps \
    glib \
    glib-networking \
    glpk \
    gmp \
    gnome-icon-theme \
    gnu-indent \
    gnu-sed \
    gnu-tar \
    gnu-which \
    gnuplot \
    gnutls \
    go \
    gobject-introspection \
    gprof2dot \
    gradle \
    graphicsmagick \
    graphviz \
    grep \
    groovy \
    gsettings-desktop-schemas \
    gtk+3 \
    gtk-vnc \
    gzip \
    harfbuzz \
    hdf5 \
    hicolor-icon-theme \
    htop-osx \
    icu4c \
    imagemagick \
    influxdb \
    intltool \
    isl \
    jo \
    jpeg \
    jq \
    jsoncpp \
    lame \
    lua \
    luajit \
    lzip \
    kubernetes-cli \
    macvim \
    maven \
    metis \
    mitmproxy \
    mobile-shell \
    mpfr \
    nettle \
    nmap \
    node \
    nomad \
    octave \
    oniguruma \
    openjpeg \
    openssl \
    openssl@1.1 \
    p11-kit \
    p7zip \
    packer \
    pango \
    parallel \
    pcre \
    pcre2 \
    pixman \
    pkg-config \
    plotutils \
    poppler \
    protobuf \
    pstoedit \
    py2cairo \
    pygobject3 \
    pyqt5 \
    python \
    python3 \
    qhull \
    qrupdate \
    qscintilla2 \
    qt5 \
    readline \
    rename \
    rsync \
    ruby \
    screen \
    shared-mime-info \
    sip \
    sqlite \
    ssh-copy-id \
    suite-sparse \
    sysdig \
    szip \
    tbb \
    terraform \
    texinfo \
    tmux \
    transfig \
    tree \
    utf8proc \
    vala \
    veclibfort \
    vte3 \
    watch \
    wdiff \
    webp \
    wget \
    x264 \
    xvid \
    xz \
    yajl \
    yarn \
    youtube-dl
}

function cron() {
  ansible localhost -c local -i 'localhost,' -m cron -a 'name="brew list" state=present minute="2" job="path=/Users/`whoami`/Drive/Workstation/$(echo `hostname` | cut -f 1 -d .); mkdir -p \"$path\"; /usr/local/bin/brew list > \"$path/brew_list.txt\""'
  ansible localhost -c local -i 'localhost,' -m cron -a 'name="crontab backup" state=present minute="2" job="path=/Users/`whoami`/Drive/Workstation/$(echo `hostname` | cut -f 1 -d .); mkdir -p \"$path\"; crontab -l > \"$path/crontab\""'
  ansible localhost -c local -i 'localhost,' -m cron -a 'name="bash history" state=present minute="2" job="path=/Users/`whoami`/Drive/Workstation/$(echo `hostname` | cut -f 1 -d .); mkdir -p \"$path\"; cp /Users/`whoami`/.bash_history $path"'
}

function gitconfig() {
    git config --global alias.lg 'log --graph --abbrev-commit --decorate --date=relative'
    git config --global alias.lgs 'log --graph --oneline --decorate --date=relative --all'
    git config --global alias.amend 'commit --amend --no-edit'

    git config --global user.name 'Henrique Gontijo'
    git config --global user.email 'hgontijo@guidewire.com'

    git config --global pull.rebase true
    git config --global push.default simple
    git config --global core.excludesfile '/Users/hgontijo/.gitignore_global'
}

function usage() {
  echo -e "Basic setup for a macOS.\n"
  echo "Usage:"
  echo "  base                        - install base packages"
  echo "  cron                        - setup cron"
  echo "  gitconfig                   - git config"
}
